In [1]:
# Initialize OK
from client.api.notebook import Notebook
# ok = Notebook('ps02.ok')

# Problem set 2. Modeling humanity's economic growth watersheds

These problem set assignments are a required part of the course.

Collaborating on the problem sets is more than okay—it is encouraged! Seek help from a classmate or an instructor or a roommate or a passerby when you get stuck! (Explaining things is beneficial, too—the best way to solidify your knowledge of a subject is to explain it.) 

But the work has to be your own: no cutting-&-pasting from others' problem sets, please! We want you to learn this stuff, and your fingers typing every keystroke is an important way of building muscle memory here.

In this problem set, you will take a look at the very long-term structure of human economic history since the invention of agriculture 8000 years ago. It is, overwhelmingly, a story of innovation, fecundity and demography, and resources.

Let us get started!

# 1. Preliminaries

### A. Computing environment

First, we set up the computing environment:

In [2]:
# set up the computing environment: import libraries, & ensure
# that graphs appear inline in the notebook & not in extra
# windows:

%matplotlib inline
import numpy as np
import pandas as pd
import matplotlib as mpl
import matplotlib.pyplot as plt

&nbsp;

### B. Repeating problem set 1

Recall our estimates of humanity's economy in the very long run from the last problem set. Let's repeat their construction:

In [5]:
# repeating the work of problem set 1:

long_run_growth_list = [
    [-68000, 379.47, 1200, 0.1],
    [-8000, 1897.37, 1200, 2.5],
    [-6000, 2381.18, 900, 7],
    [-3000, 3485.68, 900, 15],
    [-1000, 6363.96, 900, 50],
    [1, 11734.56, 900, 170],
    [1500, 20124.61, 900, 500],
    [1770, 30124.74, 1100, 750],
    [1870, 46872.17, 1300, 1300],
    [2020, 1032370.8, 11842, 7600]
    ]

long_run_growth_df = pd.DataFrame(
  data=np.array(long_run_growth_list), columns = ['year', 
  'human_ideas_index', 'income_level', 'population']
  )

long_run_growth_df['year'] = long_run_growth_df['year'].apply(np.int64)

initial_year = long_run_growth_df['year'][0:10]

span = []
g = []
h = []
n = []

for t in range(9):
    span = span +[long_run_growth_df['year'][t+1]-long_run_growth_df['year'][t]]
    h = h + [np.log(long_run_growth_df['human_ideas_index'][t+1]/long_run_growth_df['human_ideas_index'][t])/span[t]]
    g = g + [np.log(long_run_growth_df['income_level'][t+1]/long_run_growth_df['income_level'][t])/span[t]]
    n = n + [np.log(long_run_growth_df['population'][t+1]/long_run_growth_df['population'][t])/span[t]]
    
long_run_growth_df.set_index('year', inplace=True)

# finally, add a note to the end of each observation, reminding
# us of what was going on in human history back in each of the
# eras into which we have divided it

eras = ['at the dawn', 'agriculture & herding', 'proto-agrarian age',
        'writing', 'axial age', 'dark & middle age slowdown', 'commercial revolution',
        'industrial revolution', 'modern economic growth', 'whatever the 21st century brings']

long_run_growth_df['eras'] = eras

format_dict = {'year': '{d}', 'human_ideas_index': '{0:,.0f}', 
    'income_level': '${0:,.0f}', 'population': '{0:,.1f}'}

long_run_growth_df.style.format(format_dict)

In [6]:
data_list = np.array([span, h, g, n]).transpose()

long_run_growth_rates_df = pd.DataFrame(
    data=data_list, columns = ['span', 'h', 'g', 'n'])

long_run_growth_rates_df['initial_year'] = initial_year

eras2 = eras[0:9]

long_run_growth_rates_df['era'] = eras2

format_dict = {'initial_year':'{0:.0f}',  'span': '{0:.0f}', 'h': '{0:,.3%}', 
    'g': '{0:,.2%}', 'n': '{0:,.2%}'}

long_run_growth_rates_df.style.format(format_dict)

### C. My take on what we see here

Again, repeating what we saw last problem set:

There are some obvious things to get from these numbers. Here is my take:

The invention of agriculture—or perhaps it was the settling-down—mattered.

Before 8000 years ago, most invention and innovation was figuring out what light and easy-to-carry tools you needed to flourish in new or changing environments.

After 8000 years ago, invention and innovation got charged: stable location and population density greatly expanded what stuff could be useful, and greatly aided social memory. The rate of increase of the stock of valuable ideas about technology and organization quadrupled with the coming of agriculture. We can see the coming of agriculture as the first major watershed in the story of very long-run human economic history.

Moreover, over the next several thousand years there was definitely a two-heads-are-better-than-one phenomenon as more people applying their brains and communicating with each other further increased the rate of growth. We saw a further doubling of the proportional pace of growth of the human useful ideas stock with the coming of cities (and their power to dominate and concentrate resources), record-keeping, and reading 5000 years ago. We saw a further doubling 3000 years ago, with the coming of civilization: what some call the “axial age”.

But then, after about the year one (probably better-dated to 150) according to the most-used current calendar, the proportional growth rate of the ideas stock dropped. Before the year one, we could say that humanity, considered as a time-binding anthology intelligence, was undergoing super-exponential growth in its knowledge and capabilities. After the year one—or 150–that was no longer true. We can see this arrival of the mid-first millennium Eurasian dark age—the late-antiquity pause—as a second watershed.

Then, starting around 1500, we see three more watersheds:

(1) The coming of the commercial revolution era and the knitting together economically of the entire world via ocean transport produced a renewed worldwide acceleration in the proportional pace of ideas-stock growth: roughly a quadrupling, to rates of growth that had never been seen outside of areas in the Mediterranean, Mesopotamia, or north China that were relatively small portions of the globe. 

(2) 1770 saw the coming of the industrial revolution era, at first very highly concentrated in the northwestern tip of Eurasian continent: it more than tripled the proportional rate of ideas stock growth from its already unprecedentedly high level. 

(3) Then, about a century later, with the coming (a) of full globalization as we know it, (b) of the industrial research lab to rationalize and routinize the creation and development of technologies, and (c) of the modern corporation to rationalize and routinize their global deployment, came the era of modern economic growth that we live in. Since 1870 or so, the proportional growth rate of the human ideas stock has not been the 0.035% per year of the first millennium and a half, or the 0.15% per year of the commercial revolution era, or even the 0.45% per year of the 1770 to 1870 industrial revolution era. It has, rather, been more than four times as great as even this last: more than 2% per year.

That is the "innovation" part of very long-run human economic history since the invention of agriculture. How about the "fecundity and demography" part? And the "resources" part?

It is a fact that the typical human of 1500 lived little or no better than the typical human of -3000. 

Atypical humans, of course, lived much better in 1500: Gilgamesh, King of Uruk in -3000, may or may not have been absolute master of thousands, but for him the consumption goods at his disposal we’re little more than bread and meat for nourishment, fleeces and simple textiles to lie on for comfort, and beer for amusement-Even to obtain cedarwood required, for Gilgamesh, a significant military expedition and struggle. 

But the typical human standard of living was set by Malthusian pressure: People sought to increase their numbers over the generations. But slow growth of technology limited the long run rate of population increase to perhaps twice the slow rate of ideas stock growth. What was the mechanism? Limited resources. Because of limited resources, more mouths meant each had to be fed off of a smaller plot of land. Even though each mouth comes with two hands, average productivity fell. That fall continued until nutrition was poor enough that disease and famine carried enough people away to limit population growth to the Malthusian warranted rate. That kept the bulk of humanity poor: a standard of living equivalent, roughly, to what the World Bank today would call $2.50 a day.

With the growth acceleration of the commercial revolution 1500 to 1770, technology begin to gain a few steps on fecundity—the potato and maize-corn were big players here. 

With the 1770 to 1870 industrial revolution saw more. The world in 1870 had a previously-unimaginable 1.3 billion people. They livedf at a typical standard of not 2.50 but perhaps 4 a day.

But it is the post-1870 modern economic growth that has seen the real explosion of wealth. And it has been coupled with the demographic transition. Humanity has decided it is rich enough to be able to afford to and to desire to restrict its fertility. So we now approach zero population growth.

We now have almost 50 times as many people on the earth living almost 15 times as well as we had back in the year one.

How do we model and understand in this?

&nbsp;

# 3. Modeling Very Long Run Economic History

In this section let us have you do some of the work...

We are going to build and apply a very simple Malthusian model of the human race's economy. It is going to have three behavioral relationships:

(1) The average level of production and income E will be the **production function** of the current population P and the current level of the ideas stock H: $ E = H P^{-1/ɣ} $

(2) The **innovation function** determines that the proportional growth rate h of the ideas stock H will be—in each era—a constant value: $ \frac{dH/dt}{H} = h $

(3) The **reproduction function** determines that the rate of growth n of the human population P depends on the average level of production and income E: $ \frac{dP/dt}{P} = n = β  \left( \frac{E}{ϕ y_{sub}}-1 \right) $

These three behavioral relatiionships have a bunch of parameters in them that determine their shape. The **production function** has a parameter ɣ, which governs how much more important ideas are in boosting productivity than limited resources are in sapping productivity. The boring **innovation function** has its one parameter, its constant value h. The **reproduction function** has three parameters: β that tells us how much population growth accelerates or decelerates as living standards rise and fall; ϕ that tells us how much larger income is than is spending on goods that actually matter for health, fitness, and population growth;  and $ y_{sub} $ that tells us at what level of spending on "fitness" or "subsistence" goods is human health and nutrition so poor that the population does not grow.

How does an economy and, indeed, a species governed by these three behavioral relationship evolve and develop over time? Let us see:

In [7]:
# first, let us set up four empty lists of numbers. we will
# make the python interpreter march through time, calculating
# what the numbers of humanity are, the typical standard of
# living, and the index of technology are at each moment we
# examine. we will then want to keep track of those three 
#quantities, and of the date to which they apply:
t_list = []
P_list = []
E_list = []
H_list = []


# start the model in the year -6000, and tell the python interpreter
# that that is the current moment: t_current
#
# also tell the python interpreter that the population at that
# current moment is 7 million people, and that the standard of
# living averages 900 a year:
t_current = -6000
P_current = 7
E_current = 900

# check to make sure that everything is what it should be:
print('the next line should be: "-6000, 7, 900"')
print(t_current, P_current, E_current)

the next line should be: "-6000, 7, 900"
-6000 7 900

In [8]:
# assign a value to the parameter ɣ, & then calculate what the value of
# H is that corresponds to the current P and E so that our equation (1)
# works:
ɣ = 2
H_current = E_current * P_current**(1/ɣ) # think of H as what E would be if the population were 1 million...


# remember the empty lists we started with? update them by adding the 
# current values of t, P, E, and H to the ends of the respective lists:
t_list = t_list + [t_current]
P_list = P_list + [P_current]
E_list = E_list + [E_current]
H_list = H_list + [H_current]


# set our other parameters:
β = 0.025
ϕ = 1
y_sub = 890.7364
h_growth = 0.000126


# & tell the python interpreter how large a step we want it to take
# as it projects the model through history. does it want each step
# to be one year? we could, but since history happens slowly at the
# start, let us set the computer to look at the economy only once a
# century:
t_growth = 100

In [9]:
# now we use a loop structure to move forward in time from our initial
# current year of -6000, 100 years at a clip:
for i in range(30):
    t_current = t_current + t_growth # we move our time stamp ahead
    n = β * (E_current/(ϕ*y_sub) - 1) # this is our behavioral relationship (3)
    P_current = np.exp(n * t_growth) * P_current # we compound the population 
#     growth rate for 100 years to see what the next "P_current" will be 
    H_current = np.exp(h_growth * t_growth) * H_current # we compound 
#     the ideas growth rate for 100 years to see what the next 
#     "H_current" will be
    E_current = E_current = H_current * P_current**(-1/ɣ) # calculate the next "E_current"

# add the newly-calculated current-period variables to the respective lists
    t_list = t_list + [t_current]
    P_list = P_list + [P_current]
    E_list = E_list + [E_current]
    H_list = H_list + [H_current]
# then go back and run through the list again to advance time some more... & do this 30 times...

# check to see that at least one of the objects created looks like it is supposed to:
H_list

[2381.176179958132,
 2411.368813972403,
 2441.944281964434,
 2472.907438159744,
 2504.2631983340452,
 2536.0165405936837,
 2568.172506165971,
 2600.7362001995416,
 2633.7127925748578,
 2667.107518724989,
 2700.925680466801,
 2735.1726468426846,
 2769.8538549729537,
 2804.974810919056,
 2840.541090557725,
 2876.5583404662207,
 2913.0322788187887,
 2949.9686962944925,
 2987.3734569965513,
 3025.25249938334,
 3063.611837211189,
 3102.4575604891425,
 3141.795836445819,
 3181.6329105085365,
 3221.9751072948466,
 3262.8288316166463,
 3304.200569497019,
 3346.096889199967,
 3388.524442273206,
 3431.4899646041777,
 3475.0002774894515]

In [10]:
# now stuff our collection of lists into a dataframe to take a look at it
# labeling its columns, and then taking a peek:
malthus_df = pd.DataFrame(np.array([t_list, P_list, E_list, H_list])).transpose()
malthus_df.columns = ['date', 'population', 'income_level', 'human_ideas']
malthus_df['date'] = malthus_df['date'].apply(np.int64)

format_dict = {'human_ideas': '{0:,.0f}', 
    'income_level': '${0:,.0f}', 'population': '{0:,.2f}'}

malthus_df.style.format(format_dict)

If everything went well, you will find that you (close to) replicated how ideas H, population P, and income and labor-efficiency E evolved in history from the year -6000 to -3000. 

If you do not see, immediately above, a table with -3000 (the last year calculated) as the first entry in its last line, and its other entries as close to 14.9 (the population in -3000), 899.7 (income per capita E in -3000), and 3475.0 (H in -3000), go back and try to figure out where the error is.

Satified and happy? Good.

The code cell above does simple calculations. But it does a lot of them. And we will want to repeat those calculations a number of times, for different starting dates, periods, and parameter values. So I am next going to stuff all of those calculations into a function I will call "malthus_update". Why? So that for the rest of this notebook, whenever you or I want to do calculations like those in the code cell immediately above, all you or I will have to do is to write a code line like:

>output = malthus_update()

putting the appropriate symbols to tell the computer for what parameter values, what starting position, and over what period we wish the calculations, and then stuff the results into an object called "output" that we can then tell the computer to use.

Here is the function, with its defaults set to reproduce the -6000 to -3000 model run above:

In [11]:
# definition of the malthus_update function:

def malthus_update(t_current = -6000, t_growth = 100, horizon = 30, 
  P_current = 7, E_current = 900, h_growth = 0.000126, ɣ = 2, 
  β = 0.025, ϕ = 1, y_sub = 890.7364):
    """
    Updates the three-variable Malthusian model—population, income, 
    technology—from starting year t_current, stepping through time
    with a step of t_growth, for t_growth x horizon years
    """
    
    P_list = []
    t_list = []
    E_list = []
    H_list = []

    H_current = E_current * P_current**(1/ɣ) # think of H as what E would be if the population were 1 million...

    P_list = P_list + [P_current]
    t_list = t_list + [t_current]
    E_list = E_list + [E_current]
    H_list = H_list + [H_current]

    for i in range(horizon):
        P_growth = β * (E_current/(ϕ*y_sub) - 1)
        P_current = np.exp(P_growth * t_growth) * P_current
        t_current = t_current + t_growth
        H_current = np.exp(h_growth * t_growth) * H_current
        E_current = E_current = H_current * P_current**(-1/ɣ)

        P_list = P_list + [P_current]
        t_list = t_list + [t_current]
        E_list = E_list + [E_current]
        H_list = H_list + [H_current]
        
    update = [t_list, P_list, E_list, H_list]
    return(update)

Does it work? Let's call it from the vasty deep, letting it do what its defaults say it should do, and see:

In [12]:
# calling malthus_update() with defaults:

output = malthus_update()

malthus2_df = pd.DataFrame(np.array(output)).transpose()

malthus2_df.columns = ['date', 'population', 'income_level', 'human_ideas']
malthus2_df['date'] = malthus2_df['date'].apply(np.int64)

format_dict = {'human_ideas': '{0:,.0f}', 
    'income_level': '${0:,.0f}', 'population': '{0:,.2f}'}

malthus2_df.style.format(format_dict)

Did it work? It worked on my machine, at least.

Now let us look forward and look over -3000 to -1000. We are going to have to change what we tell malthus_update to do. We are going to have to tell it that we want it to start in year -3000: tell it "t_current = -3000". We are going to want to tell it we want it to look 20 periods ahead to get from -3000 to -1000: "horizon = 20". We are going to want to tell it that we want it to start with the initial population P_current and the initial income level E_current at their historical -3000 values. Accomplish all those, and track the economy forward another 2000 years to -1000.

In [13]:
# from -3000 to -1000: a doubling of h:

output = malthus_update(t_current = -3000, horizon = 20, h_growth = 0.00031, 
  P_current = 15, E_current = 900)

malthus3_df = pd.DataFrame(np.array(output)).transpose()

malthus3_df.columns = ['date', 'population', 'income_level', 'human_ideas']
malthus3_df['date'] = malthus3_df['date'].apply(np.int64)

format_dict = {'human_ideas': '{0:,.0f}', 
    'income_level': '${0:,.0f}', 'population': '{0:,.2f}'}

malthus3_df.style.format(format_dict)

Did it work? If not, try to figure out why, and rerun it.

Now we wish to go forward from -1000 to the year 0. (Yes, math does not play well with a calendar that does not have a year 0 in it. If you are upset enough, find a time machine and take it back to the year 500, to the of Constanta in what is now Roumania, and argue with the monk Dionysius Exiguus—Denny the Dwarfish—who landed us with this system.) See if you can set up malthus_update to use an ideas stock growth rate of 0.064%/year to calculate a population of about 70 million, an income level of about 936 dollars per capita per year, and a technology index in year zero of about 12243, all in the year 0... 1. Blame Denny:

In [14]:
## from -1000 to the year 1: a further doubling of h:

output = malthus_update(t_current = -1000, horizon = 10, h_growth = 0.00064, 
  P_current = 50, E_current = 913)

malthus4_df = pd.DataFrame(np.array(output)).transpose()

malthus4_df.columns = ['date', 'population', 'income_level', 'human_ideas']
malthus4_df['date'] = malthus4_df['date'].apply(np.int64)

format_dict = {'human_ideas': '{0:,.0f}', 
    'income_level': '${0:,.0f}', 'population': '{0:,.0f}'}

malthus4_df.style.format(format_dict)

So far I have just made you demonstrate that the model is consistent: Given these behavioral relationships and given this definition of H and of the changes in its growth rate, we can replicate human economic history at the broadest possible level from the year -6000 to the year 0... 1... whatever.

Now things get more substantive and, I hope, more interesting to you.

We had proportional growth rates of h of about 0.013%/year from -6000 to -3000, of about 0.031%/year from -3000 to -1000, and of about 0.064%/year from -1000 to the year 1. Living standards were not rising much, true—Malthusian forces at work. But population, ideas, knowledge, indeed civilization seemed to be gathering strength and undergoing superexponential growth. It would have seemed reasonable in the year 1 or even the year 150 to have expected more of the same: two successive doublings of h ought to have been followed by a third in the next millennium or so. What does our model say would have been the state of the human economy in 1500 if h had undergone a further doubling, and if the years 1 to 1500 had seen an ideas growth rate h of 0.12%/year? Let us, as we economic historians like to say, "consider the counterfactual": something that did not happen, but might have happened, and then try to trace out what the consequences would have been.

Let us start are malthus_update() function with a population of 170 million and a standard of living of 935 dollars per year in year 0, and see:

In [15]:
# from year 1 to 1500: counterfactual: further doubling of h:

output = malthus_update(t_current = 0, horizon = 15, h_growth = 0.0012, 
  P_current = 170, E_current = 935)

malthus5_df = pd.DataFrame(np.array(output)).transpose()

malthus5_df.columns = ['date', 'population', 'income_level', 'human_ideas']
malthus5_df['date'] = malthus5_df['date'].apply(np.int64)

format_dict = {'human_ideas': '{0:,.0f}', 
    'income_level': '${0:,.0f}', 'population': '{0:,.0f}'}

malthus5_df.style.format(format_dict)

Compare this to what happened in actual history—actual history had a year-1500 population of only 500 million in the year 1500, rather than more than ten times as much. 

Something went wrong. It is called "the dark ages". 

After the year 1, h did not jump again from 0.06%/year to 1%/year; rather, it declined back to its pre-1000 rate of about 0.03% per year, or maybe a little higher.

Let's rerun history as it actually went:

In [16]:
# from the year 1 to 1500: historical: Dark Ages: h falls back down to 0.0035%/year

output = malthus_update(t_current = 0, horizon = 15, h_growth = 0.00035, 
  P_current = 170, E_current = 935)

malthus6_df = pd.DataFrame(np.array(output)).transpose()

malthus6_df.columns = ['date', 'population', 'income_level', 'human_ideas']
malthus6_df['date'] = malthus6_df['date'].apply(np.int64)

format_dict = {'human_ideas': '{0:,.0f}', 
    'income_level': '${0:,.0f}', 'population': '{0:,.0f}'}

malthus6_df.style.format(format_dict)

It is in the year 1500 that we see our third watershed—this time an acceleration of rather than a deceleration in growth.

But now let us consider another counterfactual.

Suppose the world had then continued after 1500 as it had gone from 1 to 1500—with a growth rate of h still equal to 0.035%/year. We can use our model to see what today's world would now be like if the commercial revolution era had never come to pass:

In [17]:
# from the year 1500 to 2000: counterfactual: h continues at 0.0035%/year

output = malthus_update(t_current = 1500, horizon = 5, h_growth = 0.00035, 
  P_current = 500, E_current = 915)

malthus7_df = pd.DataFrame(np.array(output)).transpose()

malthus7_df.columns = ['date', 'population', 'income_level', 'human_ideas']
malthus7_df['date'] = malthus7_df['date'].apply(np.int64)

format_dict = {'human_ideas': '{0:,.0f}', 
    'income_level': '${0:,.0f}', 'population': '{0:,.0f}'}

malthus7_df.style.format(format_dict)

You should have gotten a world in 2000 with a population of 708 million or so, and an income level of 915 dollars per year.

That would have been a very different world than ours, no? 1/10 the population, and 1/12 the per capita wealth. And the level of human technology in 2000 in that counterfactual no-commercial revolution world? Roughly that seen in our world in 1630 or so. 

But in fact 1500 was the third watershed. It saw the more-than-quadruling from 0.035%/year to 0.15%/year in the proportional rate h of the ideas stock. And, interestingly, demography did not fully keep pace with what one would have expected given the reaction of population growth to prosperity before 1500. In order to model this, we need not only to increase h from 0.035%/year to 0.15%/year, we need to allow for an increase in luxuries: if the parameter ϕ that tells us what total income was relative to the consumption of goods that directly affect and improve reproductive fitness, we need to raise ϕ from 1.0 before the third watershed of 1500 to 1.13 afterwards to track how innovation gained a few steps on fecundity. And it did. By 1770, historically, population had grown from 500 to 750 million. And typical living standards had risen from 900 to 1100 dollars per year: from 2.50 dollars a day to 3 dollars a day.

Use our malthus_update() function starting in 1500 to track the evolution of the human economy in this 1500-1770 commercial revolution era. And this time drop our interval length from 100 years to 10 years. Economic history, at least, was slow-moving before 1500. But now it begins to speed up, and we need to examine it more frequently:

In [18]:
# starting in 1500: historical
# an increase in luxuries: ϕ = 1.13
# a more-than-quadrupling of ideas growth: h_growth = 0.0015

output = malthus_update(t_current = 1500, horizon = 27, h_growth = 0.0015, 
  P_current = 500, E_current = 915, ϕ = 1.13, t_growth = 10)

malthus8_df = pd.DataFrame(np.array(output)).transpose()

malthus8_df.columns = ['date', 'population', 'income_level', 'human_ideas']
malthus8_df['date'] = malthus8_df['date'].apply(np.int64)

format_dict = {'human_ideas': '{0:,.0f}', 
    'income_level': '${0:,.0f}', 'population': '{0:,.0f}'}

malthus8_df.style.format(format_dict)

In our estimates, the third watershed—the more-than-quadruling from 0.035%/year to 0.15%/year in the proportional rate h of the ideas stock—was followed by a fourth: steam-power, automatic textile machinery, and improved ironmaking that allowed for the railroad and all the other innovations of the classic industrial revolution. This industrial revolution age from 1770-1870 saw, worldwide, a further tripling of the growth rate of humanity's applied technological and organization toolbox to 0.44%/year.

But once again, let us first consider a counterfactual in which it did not. Let us remove this fourth watershed from history, maintain the growth rate of h at 0.15%/year as it was in the commercial revolution era, and see where that counterfactual world is today, say this year, in 2020:

In [19]:
# since 1770: counterfactual—no industrial revolution:

output = malthus_update(t_current = 1770, horizon = 25, h_growth = 0.0015, 
  P_current = 750, E_current = 1100, ϕ = 1.13, t_growth = 10)

malthus9_df = pd.DataFrame(np.array(output)).transpose()

malthus9_df.columns = ['date', 'population', 'income_level', 'human_ideas']
malthus9_df['date'] = malthus9_df['date'].apply(np.int64)

format_dict = {'human_ideas': '{0:,.0f}', 
    'income_level': '${0:,.0f}', 'population': '{0:,.0f}'}

malthus9_df.style.format(format_dict)

You should get a population today of about 1.5 billion, and a standard of living average of about 1125 dollars per year. Prosperity thus gained a few steps on fecundity from 1500 to 1770. But thereafter the two once again kept pace. And the level of technology today in that counterfactual? It is about the level of 1860: riverboats and early railroads and textile machinery, with the first cheap rifled muskets reaching the hands of soldiers, and with telegraph wires across land but not yet in undersea cables. It would then be a steampunk world.

However, there was an industrial revolution. The 1770 to 1870 century can be tracked, maintaining the luxuries parameter ϕ = 1.13, by a further tripling of h to 0.44%/year

In [20]:
# since 1770: but there was an industrial revolution:

output = malthus_update(t_current = 1770, horizon = 10, h_growth = 0.0044, 
  P_current = 750, E_current = 1100, ϕ = 1.13, t_growth = 10)

malthus10_df = pd.DataFrame(np.array(output)).transpose()

malthus10_df.columns = ['date', 'population', 'income_level', 'human_ideas']
malthus10_df['date'] = malthus10_df['date'].apply(np.int64)

format_dict = {'human_ideas': '{0:,.0f}', 
    'income_level': '${0:,.0f}', 'population': '{0:,.0f}'}

malthus10_df.style.format(format_dict)

That carries us to the historical world we saw, with 1.3 billion people in the world in 1870, and an average living standard of 4 dollars a day: 1300 a year.

And then came the fifth watershed: a further more than quadrupling of h from 0.44% to 2.06% per year. But, once again, let us look first at the counterfactual in which that modern economic growth acceleration did not happen. What would the world be like now, if that counterfactual had become reality and h since 1870 had continued to plod along at 0.44%/year?

In [21]:
# since 1870: counterfactual: no modern economic growth:

output = malthus_update(t_current = 1870, horizon = 15, h_growth = 0.0044, 
  P_current = 1270, E_current = 1300, ϕ = 1.13, t_growth = 10)

malthus11_df = pd.DataFrame(np.array(output)).transpose()

malthus11_df.columns = ['date', 'population', 'income_level', 'human_ideas']
malthus11_df['date'] = malthus11_df['date'].apply(np.int64)

format_dict = {'human_ideas': '{0:,.0f}', 
    'income_level': '${0:,.0f}', 'population': '{0:,.0f}'}

malthus11_df.style.format(format_dict)

Contrast that with our actual history:

In [22]:
# recall actual history: a further quadrupling of h after 1870

format_dict = { 'span': '{0:.0f}', 'h': '{0:,.3%}', 
    'g': '{0:,.2%}', 'n': '{0:,.2%}'}

long_run_growth_rates_df.style.format(format_dict)

In [23]:
# with results:

format_dict = {'year': '{d}', 'human_ideas_index': '{0:,.0f}', 
    'income_level': '${0:,.0f}', 'population': '{0:,.1f}'}

long_run_growth_df.style.format(format_dict)

The counterfactual no-modern-economic-growth scenario has a world today of 4.4 billion, but a typical living standard of 1350 dollars per year—3 2/3 dollars a day. And its level of technology? About that of 1900-1910. Technology would be a little bit post-steampunk—there would be internal combustion engines, and experiments with heavier-than-air flying machines. And it would be a populous world—but one still very, very poor.

In [24]:
# since 1870: counterfactual: modern economic growth but no demographic transition:

output = malthus_update(t_current = 1870, horizon = 15, h_growth = 0.0206, 
  P_current = 1270, E_current = 1300, ϕ = 1.13, t_growth = 10)

malthus12_df = pd.DataFrame(np.array(output)).transpose()

malthus12_df.columns = ['date', 'population', 'income_level', 'human_ideas']
malthus12_df['date'] = malthus12_df['date'].apply(np.int64)

format_dict = {'human_ideas': '{0:,.0f}', 
    'income_level': '${0:,.0f}', 'population': '{0:,.0f}'}

malthus12_df.style.format(format_dict)

$ E = H P^{-1/\gamma} $

$ H = E P^{1/\gamma} $

Remember:

* The year at which an observation is made we will call t for year
* The stock of useful human ideas about technology and organization we will call H or human_ideas
* The level of labor efficiency or productivity we will E. 
* In this notetook E will be the same as productivity or real income per capita, which we will otherwise call  y or income_level
* The level of human population we will call P or population

$ \frac{dPop/dt}{Pop} = \frac{d\ln(Pop)}{dt} = n = \beta  \left( \frac{y}{\phi y_{sub}}-1 \right) $

Where:

* ϕ is consumption relative to fitness-good consumption—i.e., an index of how much is spent on luxuries
* $ y_{sub} $ is the subsistence level of fitness-good consumption—the level of fitness-good consumption at which Malthusian forces make population stable.
* β is how much population growth increases when fitness-good consumption rises above subsistence

# 6. You are done!

You're done with Problem set 0!  Be sure to run the tests and verify that they all pass, then choose **Save and Checkpoint** from the **File** menu, then **run the final cell** to submit your work.  If you submit multiple times, your last submission will be counted.

**Important.** In order to get credit, you need to run the final code cell below to submit your work:

In [ ]:
# this cell is commented out; 

# _ = ok.submit()